/*
 * XTRF Home Portal API
 * XTRF Home Portal API enables you to perform operations on Projects, Quotes, Customers, Vendors etc. as a XTRF Home Portal user. <br>The documentation is generated from OpenAPI specification 3.0 available <a href=\"/home-api/openapi.json\">here</a> <br>   The API client/consumer code may be easily generated in 60+ programming languages using an open source code generator available at the time of writing this documentation at <a href='https://editor.swagger.io/'>https://editor.swagger.io/</a> Thank you for using XTRF Application Programming interface (XTRF API). By using the API you agree to the terms below. If you disagree with any of these terms, XTRF does not grant you a license to use the XTRF API. XTRF reserves the right to update and change these terms from time to time without a prior notice of API users. You can always find the most recent version of these terms here: 
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * CustomerInvoiceCreateResultDTO
 */


public class CustomerInvoiceCreateResultDTO {
  @SerializedName("invoicesIds")
  private List<Long> invoicesIds = null;

  @SerializedName("invoiceUrl")
  private String invoiceUrl = null;

  public CustomerInvoiceCreateResultDTO invoicesIds(List<Long> invoicesIds) {
    this.invoicesIds = invoicesIds;
    return this;
  }

  public CustomerInvoiceCreateResultDTO addInvoicesIdsItem(Long invoicesIdsItem) {
    if (this.invoicesIds == null) {
      this.invoicesIds = new ArrayList<Long>();
    }
    this.invoicesIds.add(invoicesIdsItem);
    return this;
  }

   /**
   * Get invoicesIds
   * @return invoicesIds
  **/
  @Schema(description = "")
  public List<Long> getInvoicesIds() {
    return invoicesIds;
  }

  public void setInvoicesIds(List<Long> invoicesIds) {
    this.invoicesIds = invoicesIds;
  }

  public CustomerInvoiceCreateResultDTO invoiceUrl(String invoiceUrl) {
    this.invoiceUrl = invoiceUrl;
    return this;
  }

   /**
   * Get invoiceUrl
   * @return invoiceUrl
  **/
  @Schema(description = "")
  public String getInvoiceUrl() {
    return invoiceUrl;
  }

  public void setInvoiceUrl(String invoiceUrl) {
    this.invoiceUrl = invoiceUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerInvoiceCreateResultDTO customerInvoiceCreateResultDTO = (CustomerInvoiceCreateResultDTO) o;
    return Objects.equals(this.invoicesIds, customerInvoiceCreateResultDTO.invoicesIds) &&
        Objects.equals(this.invoiceUrl, customerInvoiceCreateResultDTO.invoiceUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(invoicesIds, invoiceUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerInvoiceCreateResultDTO {\n");
    
    sb.append("    invoicesIds: ").append(toIndentedString(invoicesIds)).append("\n");
    sb.append("    invoiceUrl: ").append(toIndentedString(invoiceUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
