/*
 * XTRF Home Portal API
 * XTRF Home Portal API enables you to perform operations on Projects, Quotes, Customers, Vendors etc. as a XTRF Home Portal user. <br>The documentation is generated from OpenAPI specification 3.0 available <a href=\"/home-api/openapi.json\">here</a> <br>   The API client/consumer code may be easily generated in 60+ programming languages using an open source code generator available at the time of writing this documentation at <a href='https://editor.swagger.io/'>https://editor.swagger.io/</a> Thank you for using XTRF Application Programming interface (XTRF API). By using the API you agree to the terms below. If you disagree with any of these terms, XTRF does not grant you a license to use the XTRF API. XTRF reserves the right to update and change these terms from time to time without a prior notice of API users. You can always find the most recent version of these terms here: 
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * JobFilesDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-07-02T16:14:58.802Z[GMT]")
public class JobFilesDto {
  @SerializedName("sharedWorkFiles")
  private List<String> sharedWorkFiles = null;

  @SerializedName("sharedReferenceFiles")
  private List<String> sharedReferenceFiles = null;

  @SerializedName("deliveredInJobFiles")
  private List<String> deliveredInJobFiles = null;

  public JobFilesDto sharedWorkFiles(List<String> sharedWorkFiles) {
    this.sharedWorkFiles = sharedWorkFiles;
    return this;
  }

  public JobFilesDto addSharedWorkFilesItem(String sharedWorkFilesItem) {
    if (this.sharedWorkFiles == null) {
      this.sharedWorkFiles = new ArrayList<String>();
    }
    this.sharedWorkFiles.add(sharedWorkFilesItem);
    return this;
  }

   /**
   * Get sharedWorkFiles
   * @return sharedWorkFiles
  **/
  @Schema(description = "")
  public List<String> getSharedWorkFiles() {
    return sharedWorkFiles;
  }

  public void setSharedWorkFiles(List<String> sharedWorkFiles) {
    this.sharedWorkFiles = sharedWorkFiles;
  }

  public JobFilesDto sharedReferenceFiles(List<String> sharedReferenceFiles) {
    this.sharedReferenceFiles = sharedReferenceFiles;
    return this;
  }

  public JobFilesDto addSharedReferenceFilesItem(String sharedReferenceFilesItem) {
    if (this.sharedReferenceFiles == null) {
      this.sharedReferenceFiles = new ArrayList<String>();
    }
    this.sharedReferenceFiles.add(sharedReferenceFilesItem);
    return this;
  }

   /**
   * Get sharedReferenceFiles
   * @return sharedReferenceFiles
  **/
  @Schema(description = "")
  public List<String> getSharedReferenceFiles() {
    return sharedReferenceFiles;
  }

  public void setSharedReferenceFiles(List<String> sharedReferenceFiles) {
    this.sharedReferenceFiles = sharedReferenceFiles;
  }

  public JobFilesDto deliveredInJobFiles(List<String> deliveredInJobFiles) {
    this.deliveredInJobFiles = deliveredInJobFiles;
    return this;
  }

  public JobFilesDto addDeliveredInJobFilesItem(String deliveredInJobFilesItem) {
    if (this.deliveredInJobFiles == null) {
      this.deliveredInJobFiles = new ArrayList<String>();
    }
    this.deliveredInJobFiles.add(deliveredInJobFilesItem);
    return this;
  }

   /**
   * Get deliveredInJobFiles
   * @return deliveredInJobFiles
  **/
  @Schema(description = "")
  public List<String> getDeliveredInJobFiles() {
    return deliveredInJobFiles;
  }

  public void setDeliveredInJobFiles(List<String> deliveredInJobFiles) {
    this.deliveredInJobFiles = deliveredInJobFiles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobFilesDto jobFilesDto = (JobFilesDto) o;
    return Objects.equals(this.sharedWorkFiles, jobFilesDto.sharedWorkFiles) &&
        Objects.equals(this.sharedReferenceFiles, jobFilesDto.sharedReferenceFiles) &&
        Objects.equals(this.deliveredInJobFiles, jobFilesDto.deliveredInJobFiles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sharedWorkFiles, sharedReferenceFiles, deliveredInJobFiles);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobFilesDto {\n");
    
    sb.append("    sharedWorkFiles: ").append(toIndentedString(sharedWorkFiles)).append("\n");
    sb.append("    sharedReferenceFiles: ").append(toIndentedString(sharedReferenceFiles)).append("\n");
    sb.append("    deliveredInJobFiles: ").append(toIndentedString(deliveredInJobFiles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
