/*
 * XTRF Home Portal API
 * XTRF Home Portal API enables you to perform operations on Projects, Quotes, Customers, Vendors etc. as a XTRF Home Portal user. <br>The documentation is generated from OpenAPI specification 3.0 available <a href=\"/home-api/openapi.json\">here</a> <br>   The API client/consumer code may be easily generated in 60+ programming languages using an open source code generator available at the time of writing this documentation at <a href='https://editor.swagger.io/'>https://editor.swagger.io/</a> Thank you for using XTRF Application Programming interface (XTRF API). By using the API you agree to the terms below. If you disagree with any of these terms, XTRF does not grant you a license to use the XTRF API. XTRF reserves the right to update and change these terms from time to time without a prior notice of API users. You can always find the most recent version of these terms here: 
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.LanguageRelationDto;
import io.swagger.client.model.ProjectFileAddedByDto;
import io.swagger.client.model.RemoteCATToolReferencesDto;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ProjectFileDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-07-02T16:14:58.802Z[GMT]")
public class ProjectFileDto {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("size")
  private Long size = null;

  @SerializedName("lastModifiedOn")
  private Long lastModifiedOn = null;

  @SerializedName("categoryKey")
  private String categoryKey = null;

  @SerializedName("languageRelation")
  private LanguageRelationDto languageRelation = null;

  @SerializedName("addedBy")
  private ProjectFileAddedByDto addedBy = null;

  @SerializedName("addedInStep")
  private Long addedInStep = null;

  @SerializedName("addedInJob")
  private String addedInJob = null;

  @SerializedName("addedInLastStep")
  private Boolean addedInLastStep = null;

  @SerializedName("sharedWithJobs")
  private List<String> sharedWithJobs = null;

  @SerializedName("remoteCATToolReferences")
  private RemoteCATToolReferencesDto remoteCATToolReferences = null;

  @SerializedName("url")
  private String url = null;

  @SerializedName("isAccepted")
  private Boolean isAccepted = null;

  @SerializedName("isLink")
  private Boolean isLink = null;

  @SerializedName("isRemote")
  private Boolean isRemote = null;

  public ProjectFileDto id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ProjectFileDto name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ProjectFileDto size(Long size) {
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @Schema(description = "")
  public Long getSize() {
    return size;
  }

  public void setSize(Long size) {
    this.size = size;
  }

  public ProjectFileDto lastModifiedOn(Long lastModifiedOn) {
    this.lastModifiedOn = lastModifiedOn;
    return this;
  }

   /**
   * Get lastModifiedOn
   * @return lastModifiedOn
  **/
  @Schema(description = "")
  public Long getLastModifiedOn() {
    return lastModifiedOn;
  }

  public void setLastModifiedOn(Long lastModifiedOn) {
    this.lastModifiedOn = lastModifiedOn;
  }

  public ProjectFileDto categoryKey(String categoryKey) {
    this.categoryKey = categoryKey;
    return this;
  }

   /**
   * Get categoryKey
   * @return categoryKey
  **/
  @Schema(description = "")
  public String getCategoryKey() {
    return categoryKey;
  }

  public void setCategoryKey(String categoryKey) {
    this.categoryKey = categoryKey;
  }

  public ProjectFileDto languageRelation(LanguageRelationDto languageRelation) {
    this.languageRelation = languageRelation;
    return this;
  }

   /**
   * Get languageRelation
   * @return languageRelation
  **/
  @Schema(description = "")
  public LanguageRelationDto getLanguageRelation() {
    return languageRelation;
  }

  public void setLanguageRelation(LanguageRelationDto languageRelation) {
    this.languageRelation = languageRelation;
  }

  public ProjectFileDto addedBy(ProjectFileAddedByDto addedBy) {
    this.addedBy = addedBy;
    return this;
  }

   /**
   * Get addedBy
   * @return addedBy
  **/
  @Schema(description = "")
  public ProjectFileAddedByDto getAddedBy() {
    return addedBy;
  }

  public void setAddedBy(ProjectFileAddedByDto addedBy) {
    this.addedBy = addedBy;
  }

  public ProjectFileDto addedInStep(Long addedInStep) {
    this.addedInStep = addedInStep;
    return this;
  }

   /**
   * Get addedInStep
   * @return addedInStep
  **/
  @Schema(description = "")
  public Long getAddedInStep() {
    return addedInStep;
  }

  public void setAddedInStep(Long addedInStep) {
    this.addedInStep = addedInStep;
  }

  public ProjectFileDto addedInJob(String addedInJob) {
    this.addedInJob = addedInJob;
    return this;
  }

   /**
   * Get addedInJob
   * @return addedInJob
  **/
  @Schema(description = "")
  public String getAddedInJob() {
    return addedInJob;
  }

  public void setAddedInJob(String addedInJob) {
    this.addedInJob = addedInJob;
  }

  public ProjectFileDto addedInLastStep(Boolean addedInLastStep) {
    this.addedInLastStep = addedInLastStep;
    return this;
  }

   /**
   * Get addedInLastStep
   * @return addedInLastStep
  **/
  @Schema(description = "")
  public Boolean isAddedInLastStep() {
    return addedInLastStep;
  }

  public void setAddedInLastStep(Boolean addedInLastStep) {
    this.addedInLastStep = addedInLastStep;
  }

  public ProjectFileDto sharedWithJobs(List<String> sharedWithJobs) {
    this.sharedWithJobs = sharedWithJobs;
    return this;
  }

  public ProjectFileDto addSharedWithJobsItem(String sharedWithJobsItem) {
    if (this.sharedWithJobs == null) {
      this.sharedWithJobs = new ArrayList<String>();
    }
    this.sharedWithJobs.add(sharedWithJobsItem);
    return this;
  }

   /**
   * Get sharedWithJobs
   * @return sharedWithJobs
  **/
  @Schema(description = "")
  public List<String> getSharedWithJobs() {
    return sharedWithJobs;
  }

  public void setSharedWithJobs(List<String> sharedWithJobs) {
    this.sharedWithJobs = sharedWithJobs;
  }

  public ProjectFileDto remoteCATToolReferences(RemoteCATToolReferencesDto remoteCATToolReferences) {
    this.remoteCATToolReferences = remoteCATToolReferences;
    return this;
  }

   /**
   * Get remoteCATToolReferences
   * @return remoteCATToolReferences
  **/
  @Schema(description = "")
  public RemoteCATToolReferencesDto getRemoteCATToolReferences() {
    return remoteCATToolReferences;
  }

  public void setRemoteCATToolReferences(RemoteCATToolReferencesDto remoteCATToolReferences) {
    this.remoteCATToolReferences = remoteCATToolReferences;
  }

  public ProjectFileDto url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @Schema(description = "")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public ProjectFileDto isAccepted(Boolean isAccepted) {
    this.isAccepted = isAccepted;
    return this;
  }

   /**
   * Get isAccepted
   * @return isAccepted
  **/
  @Schema(description = "")
  public Boolean isIsAccepted() {
    return isAccepted;
  }

  public void setIsAccepted(Boolean isAccepted) {
    this.isAccepted = isAccepted;
  }

  public ProjectFileDto isLink(Boolean isLink) {
    this.isLink = isLink;
    return this;
  }

   /**
   * Get isLink
   * @return isLink
  **/
  @Schema(description = "")
  public Boolean isIsLink() {
    return isLink;
  }

  public void setIsLink(Boolean isLink) {
    this.isLink = isLink;
  }

  public ProjectFileDto isRemote(Boolean isRemote) {
    this.isRemote = isRemote;
    return this;
  }

   /**
   * Get isRemote
   * @return isRemote
  **/
  @Schema(description = "")
  public Boolean isIsRemote() {
    return isRemote;
  }

  public void setIsRemote(Boolean isRemote) {
    this.isRemote = isRemote;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectFileDto projectFileDto = (ProjectFileDto) o;
    return Objects.equals(this.id, projectFileDto.id) &&
        Objects.equals(this.name, projectFileDto.name) &&
        Objects.equals(this.size, projectFileDto.size) &&
        Objects.equals(this.lastModifiedOn, projectFileDto.lastModifiedOn) &&
        Objects.equals(this.categoryKey, projectFileDto.categoryKey) &&
        Objects.equals(this.languageRelation, projectFileDto.languageRelation) &&
        Objects.equals(this.addedBy, projectFileDto.addedBy) &&
        Objects.equals(this.addedInStep, projectFileDto.addedInStep) &&
        Objects.equals(this.addedInJob, projectFileDto.addedInJob) &&
        Objects.equals(this.addedInLastStep, projectFileDto.addedInLastStep) &&
        Objects.equals(this.sharedWithJobs, projectFileDto.sharedWithJobs) &&
        Objects.equals(this.remoteCATToolReferences, projectFileDto.remoteCATToolReferences) &&
        Objects.equals(this.url, projectFileDto.url) &&
        Objects.equals(this.isAccepted, projectFileDto.isAccepted) &&
        Objects.equals(this.isLink, projectFileDto.isLink) &&
        Objects.equals(this.isRemote, projectFileDto.isRemote);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, size, lastModifiedOn, categoryKey, languageRelation, addedBy, addedInStep, addedInJob, addedInLastStep, sharedWithJobs, remoteCATToolReferences, url, isAccepted, isLink, isRemote);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectFileDto {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    lastModifiedOn: ").append(toIndentedString(lastModifiedOn)).append("\n");
    sb.append("    categoryKey: ").append(toIndentedString(categoryKey)).append("\n");
    sb.append("    languageRelation: ").append(toIndentedString(languageRelation)).append("\n");
    sb.append("    addedBy: ").append(toIndentedString(addedBy)).append("\n");
    sb.append("    addedInStep: ").append(toIndentedString(addedInStep)).append("\n");
    sb.append("    addedInJob: ").append(toIndentedString(addedInJob)).append("\n");
    sb.append("    addedInLastStep: ").append(toIndentedString(addedInLastStep)).append("\n");
    sb.append("    sharedWithJobs: ").append(toIndentedString(sharedWithJobs)).append("\n");
    sb.append("    remoteCATToolReferences: ").append(toIndentedString(remoteCATToolReferences)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    isAccepted: ").append(toIndentedString(isAccepted)).append("\n");
    sb.append("    isLink: ").append(toIndentedString(isLink)).append("\n");
    sb.append("    isRemote: ").append(toIndentedString(isRemote)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
