/*
 * XTRF Home Portal API
 * XTRF Home Portal API enables you to perform operations on Projects, Quotes, Customers, Vendors etc. as a XTRF Home Portal user. <br>The documentation is generated from OpenAPI specification 3.0 available <a href=\"/home-api/openapi.json\">here</a> <br>   The API client/consumer code may be easily generated in 60+ programming languages using an open source code generator available at the time of writing this documentation at <a href='https://editor.swagger.io/'>https://editor.swagger.io/</a> Thank you for using XTRF Application Programming interface (XTRF API). By using the API you agree to the terms below. If you disagree with any of these terms, XTRF does not grant you a license to use the XTRF API. XTRF reserves the right to update and change these terms from time to time without a prior notice of API users. You can always find the most recent version of these terms here: 
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * RemoteCATToolReferencesDto
 */


public class RemoteCATToolReferencesDto {
  @SerializedName("catToolDocumentId")
  private String catToolDocumentId = null;

  @SerializedName("catResourceId")
  private String catResourceId = null;

  @SerializedName("editorUrl")
  private String editorUrl = null;

  public RemoteCATToolReferencesDto catToolDocumentId(String catToolDocumentId) {
    this.catToolDocumentId = catToolDocumentId;
    return this;
  }

   /**
   * Get catToolDocumentId
   * @return catToolDocumentId
  **/
  @Schema(description = "")
  public String getCatToolDocumentId() {
    return catToolDocumentId;
  }

  public void setCatToolDocumentId(String catToolDocumentId) {
    this.catToolDocumentId = catToolDocumentId;
  }

  public RemoteCATToolReferencesDto catResourceId(String catResourceId) {
    this.catResourceId = catResourceId;
    return this;
  }

   /**
   * Get catResourceId
   * @return catResourceId
  **/
  @Schema(description = "")
  public String getCatResourceId() {
    return catResourceId;
  }

  public void setCatResourceId(String catResourceId) {
    this.catResourceId = catResourceId;
  }

  public RemoteCATToolReferencesDto editorUrl(String editorUrl) {
    this.editorUrl = editorUrl;
    return this;
  }

   /**
   * Get editorUrl
   * @return editorUrl
  **/
  @Schema(description = "")
  public String getEditorUrl() {
    return editorUrl;
  }

  public void setEditorUrl(String editorUrl) {
    this.editorUrl = editorUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RemoteCATToolReferencesDto remoteCATToolReferencesDto = (RemoteCATToolReferencesDto) o;
    return Objects.equals(this.catToolDocumentId, remoteCATToolReferencesDto.catToolDocumentId) &&
        Objects.equals(this.catResourceId, remoteCATToolReferencesDto.catResourceId) &&
        Objects.equals(this.editorUrl, remoteCATToolReferencesDto.editorUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(catToolDocumentId, catResourceId, editorUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RemoteCATToolReferencesDto {\n");
    
    sb.append("    catToolDocumentId: ").append(toIndentedString(catToolDocumentId)).append("\n");
    sb.append("    catResourceId: ").append(toIndentedString(catResourceId)).append("\n");
    sb.append("    editorUrl: ").append(toIndentedString(editorUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
