/*
 * XTRF Home Portal API
 * XTRF Home Portal API enables you to perform operations on Projects, Quotes, Customers, Vendors etc. as a XTRF Home Portal user. <br>The documentation is generated from OpenAPI specification 3.0 available <a href=\"/home-api/openapi.json\">here</a> <br>   The API client/consumer code may be easily generated in 60+ programming languages using an open source code generator available at the time of writing this documentation at <a href='https://editor.swagger.io/'>https://editor.swagger.io/</a> Thank you for using XTRF Application Programming interface (XTRF API). By using the API you agree to the terms below. If you disagree with any of these terms, XTRF does not grant you a license to use the XTRF API. XTRF reserves the right to update and change these terms from time to time without a prior notice of API users. You can always find the most recent version of these terms here: 
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * StepTypeSemanticsDto
 */


public class StepTypeSemanticsDto {
  @SerializedName("canVerifyFiles")
  private Boolean canVerifyFiles = null;

  @SerializedName("isScripted")
  private Boolean isScripted = null;

  public StepTypeSemanticsDto canVerifyFiles(Boolean canVerifyFiles) {
    this.canVerifyFiles = canVerifyFiles;
    return this;
  }

   /**
   * Get canVerifyFiles
   * @return canVerifyFiles
  **/
  @Schema(description = "")
  public Boolean isCanVerifyFiles() {
    return canVerifyFiles;
  }

  public void setCanVerifyFiles(Boolean canVerifyFiles) {
    this.canVerifyFiles = canVerifyFiles;
  }

  public StepTypeSemanticsDto isScripted(Boolean isScripted) {
    this.isScripted = isScripted;
    return this;
  }

   /**
   * Get isScripted
   * @return isScripted
  **/
  @Schema(description = "")
  public Boolean isIsScripted() {
    return isScripted;
  }

  public void setIsScripted(Boolean isScripted) {
    this.isScripted = isScripted;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StepTypeSemanticsDto stepTypeSemanticsDto = (StepTypeSemanticsDto) o;
    return Objects.equals(this.canVerifyFiles, stepTypeSemanticsDto.canVerifyFiles) &&
        Objects.equals(this.isScripted, stepTypeSemanticsDto.isScripted);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canVerifyFiles, isScripted);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StepTypeSemanticsDto {\n");
    
    sb.append("    canVerifyFiles: ").append(toIndentedString(canVerifyFiles)).append("\n");
    sb.append("    isScripted: ").append(toIndentedString(isScripted)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
