/*
 * XTRF Home Portal API
 * XTRF Home Portal API enables you to perform operations on Projects, Quotes, Customers, Vendors etc. as a XTRF Home Portal user. <br>The documentation is generated from OpenAPI specification 3.0 available <a href=\"/home-api/openapi.json\">here</a> <br>   The API client/consumer code may be easily generated in 60+ programming languages using an open source code generator available at the time of writing this documentation at <a href='https://editor.swagger.io/'>https://editor.swagger.io/</a> Thank you for using XTRF Application Programming interface (XTRF API). By using the API you agree to the terms below. If you disagree with any of these terms, XTRF does not grant you a license to use the XTRF API. XTRF reserves the right to update and change these terms from time to time without a prior notice of API users. You can always find the most recent version of these terms here: 
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ColumnDTO;
import io.swagger.client.model.OrderDTO;
import io.swagger.client.model.PermissionsDTO;
import io.swagger.client.model.SettingsDTO;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ViewWithIdDTO
 */


public class ViewWithIdDTO {
  @SerializedName("columns")
  private List<ColumnDTO> columns = null;

  @SerializedName("viewId")
  private Long viewId = null;

  @SerializedName("settings")
  private SettingsDTO settings = null;

  @SerializedName("order")
  private OrderDTO order = null;

  @SerializedName("permissions")
  private PermissionsDTO permissions = null;

  public ViewWithIdDTO columns(List<ColumnDTO> columns) {
    this.columns = columns;
    return this;
  }

  public ViewWithIdDTO addColumnsItem(ColumnDTO columnsItem) {
    if (this.columns == null) {
      this.columns = new ArrayList<ColumnDTO>();
    }
    this.columns.add(columnsItem);
    return this;
  }

   /**
   * Get columns
   * @return columns
  **/
  @Schema(description = "")
  public List<ColumnDTO> getColumns() {
    return columns;
  }

  public void setColumns(List<ColumnDTO> columns) {
    this.columns = columns;
  }

  public ViewWithIdDTO viewId(Long viewId) {
    this.viewId = viewId;
    return this;
  }

   /**
   * Get viewId
   * @return viewId
  **/
  @Schema(description = "")
  public Long getViewId() {
    return viewId;
  }

  public void setViewId(Long viewId) {
    this.viewId = viewId;
  }

  public ViewWithIdDTO settings(SettingsDTO settings) {
    this.settings = settings;
    return this;
  }

   /**
   * Get settings
   * @return settings
  **/
  @Schema(description = "")
  public SettingsDTO getSettings() {
    return settings;
  }

  public void setSettings(SettingsDTO settings) {
    this.settings = settings;
  }

  public ViewWithIdDTO order(OrderDTO order) {
    this.order = order;
    return this;
  }

   /**
   * Get order
   * @return order
  **/
  @Schema(description = "")
  public OrderDTO getOrder() {
    return order;
  }

  public void setOrder(OrderDTO order) {
    this.order = order;
  }

  public ViewWithIdDTO permissions(PermissionsDTO permissions) {
    this.permissions = permissions;
    return this;
  }

   /**
   * Get permissions
   * @return permissions
  **/
  @Schema(description = "")
  public PermissionsDTO getPermissions() {
    return permissions;
  }

  public void setPermissions(PermissionsDTO permissions) {
    this.permissions = permissions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ViewWithIdDTO viewWithIdDTO = (ViewWithIdDTO) o;
    return Objects.equals(this.columns, viewWithIdDTO.columns) &&
        Objects.equals(this.viewId, viewWithIdDTO.viewId) &&
        Objects.equals(this.settings, viewWithIdDTO.settings) &&
        Objects.equals(this.order, viewWithIdDTO.order) &&
        Objects.equals(this.permissions, viewWithIdDTO.permissions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(columns, viewId, settings, order, permissions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ViewWithIdDTO {\n");
    
    sb.append("    columns: ").append(toIndentedString(columns)).append("\n");
    sb.append("    viewId: ").append(toIndentedString(viewId)).append("\n");
    sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
